### ISSUE TITLE
Integration test error: Execution failed for task ':distDocker'. "Could not find property 'jar' on task ':docker'

### ISSUE THREAD

**Issue by jorgeluengo** [Transmode/gradle-docker#113]
![image](https://cloud.githubusercontent.com/assets/25245787/26245020/81b5ee36-3c92-11e7-9040-e472a4301040.png)

I have run 

> ./gradlwe build

 and it fails with these errors.

Also, I tried to go to the example/simple folder and run the following command:

> ./gradlew docker

But it fails too, providing this message "Could not find property 'jar' on task ':docker'

**Comment by bjornmagnusson** [comment]
I cannot see any faults with this when running locally. 

Can you provide some more info on your environment and stack Trace/info mode on gradle build?

**Comment by jorgeluengo** [comment]
I have downloaded the source code in a zip file. I have decompressed it and I have run ./gradlew build .Then, the errors appeared. 
This is the information you requested:

> openjdk version "1.8.0_131"
> OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-0ubuntu1.16.10.2-b11)
> OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
> 

Any idea?

**Comment by bjornmagnusson** [comment]
yes, by using the zip download I managed to reproduce your error. This created an folder called gradle-docker-master. This has one big problem, the artifact published to maven local will then be called gradle-docker-master instead of gradle-docker as it is supposed to be named.

If you download the zip, it seems you must make sure the unpacked folder is called gradle-docker. In that case it worked for me.

Could you try this?

**Comment by jorgeluengo** [comment]
I have tried this and you are right. If I renamed the folder to gradle-docker it works. Thank you very much!
