### ISSUE TITLE
docker: "build" requires 1 argument : Need to escape space in path to Dockerfile

### ISSUE THREAD

**Issue by rlecomte** [Transmode/gradle-docker#83]
Hi,

I encountered an issue when try to build a docker image in my gradle project :

The command "docker build /path/to/dockerfile" doesn't work well if the path contain space => each part of the path will be take like a different argument by the docker daemon.

For example i got this error message with my project name as "multibranch demo" (if a replace space by underscore, it works)

~/workspace_devops/multibranch demo [master|✔] $ gradle clean buildDocker
:clean
:compileJava
:processResources
:classes
:jar
:copyDeps
:buildDocker FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':buildDocker'.
  > Docker execution failed
  *\*  Command line [docker build -t hello-valtech:1.0-SNAPSHOT /home/romain/workspace_devops/multibranch demo/build/docker] returned:
  docker: "build" requires 1 argument.**
  See 'docker build --help'.

**Comment by MALPI** [comment]
Encountered the same error. It would be worth to mention that in a FAQ at least.

**Comment by Jeskz0rd** [comment]
I'm running it on Windows 2016... having the same problem.

docker : "docker build" requires exactly 1 argument(s).

**Comment by davidgfolch** [comment]
Same here, my projects disk is called "TOSHIBA EXT" so the comand line created is:

`docker build -t gregturn/gs-spring-boot-docker:latest /media/slks/**TOSHIBA EXT**/Proyectos/spring/gs-spring-boot-docker/complete/build/docker
`
the gradle/docker plugin should escape like this:
`docker build -t gregturn/gs-spring-boot-docker:latest /media/slks/**TOSHIBA\ EXT**/Proyectos/spring/gs-spring-boot-docker/complete/build/docker`

**Comment by larryboymi** [comment]
Same problem with a clients' build due to space in jenkins folder name.

**Comment by bjornmagnusson** [comment]
Fixed in master.
Some test output:

Built from folder with space (C:\repos\git\gs-spring-boot-docker space\complete) using example from spring.io(https://spring.io/guides/gs/spring-boot-docker/)

Plugin version 1.2
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':buildDocker'.
> Docker execution failed
Command line [docker build -t gregturn/gs-spring-boot-docker:latest C:\repos\git\gs-spring-boot-docker space\complete\build\docker] returned:
"docker build" requires exactly 1 argument(s).

Plugin version 1.3-SNAPSHOT (current master)
BUILD SUCCESSFUL
